spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET:UIDWr79oQLjC57pLootqCLwpm340Ffyo5sqCG10HFWj6gYW29zTaoVd2imd2GrNVuvQ+b8ZtYUE9CsBjD9JpzQ==}
    accessTokenExpiration: 300 # 5 min
    refreshTokenExpiration: 604800 # 7 days
